version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn install -DskipTests
artifacts:
  files:
    - target/CentralAuditApi.war
    - appspec.yml
  discard-paths: yes